#!/bin/bash
rsync -a --progress --delete --exclude '*/__pycache__/*' --exclude '.git/*' /Users/ngocjr/Workspace/Project/nlp/address-standardization/stavia\
	ngocn@202.191.57.251:/home/ngocn/python-container