#!/bin/bash
rsync -chavzuP --stats --progress --exclude '*/__pycache__/*' --exclude '.git/*' ngocn@202.191.57.251:/home/ngocn/python-container/viaddnor\
	/Users/ngocjr/Workspace/Project/nlp/address-standardization/